apiVersion : apps/v1
kind: Deployment
metadata:
  name: myappimage 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myappimage
  template:
    metadata:
      labels:
        app: myappimage 
    spec:
      containers:
        - name: myappimage 
          image: myfirstacr888.azurecr.io/myappimage
          ports:
          - containerPort: 80